import targetScribble from "@/assets/target-scribble.png";
import planningIllustration from "@/assets/planning-illustration.png";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { Button } from "@/components/ui/button";
import { motion, useScroll, useTransform } from "framer-motion";
import { ArrowRight, BarChart3, BookOpen, Brain, Layers, Timer, Users } from "lucide-react";
import { useRef } from "react";
import { Link } from "react-router-dom";

const Index = () => {
    return (
        <div className="min-h-screen flex flex-col bg-background font-sans selection:bg-brand-blue/20">
            <Navbar />

            {/* Hero Section */}
            <section className="relative min-h-[85vh] flex items-center pt-20 pb-20 px-6 overflow-hidden">
                <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 md:gap-20 items-center relative z-10">
                    {/* Left Column: Text Content */}
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6 }}
                        className="text-left"
                    >
                        <h1 className="text-5xl md:text-7xl lg:text-8xl font-semibold tracking-tight text-foreground font-serif leading-[0.95] mb-6">
                            Master the <br />
                            <span className="relative inline-block">
                                <span className="relative z-10 text-brand-blue">Digital SAT</span>
                                <span className="absolute bottom-2 left-0 w-full h-3 bg-brand-blue/20 -z-0 transform -rotate-1 rounded-full"></span>
                            </span>
                        </h1>
                        <p className="text-xl md:text-2xl text-muted-foreground max-w-xl leading-relaxed font-light mb-8">
                            Practice 1000+ original questions generated by our state-of-the-art AI models
                        </p>

                        <div className="flex flex-col sm:flex-row gap-4">
                            <Link to="/auth">
                                <Button size="lg" className="h-14 px-8 text-lg rounded-full bg-foreground text-background hover:bg-foreground/90 transition-all hover:scale-105 shadow-xl shadow-black/5">
                                    Go to Dashboard
                                    <ArrowRight className="ml-2 h-5 w-5" />
                                </Button>
                            </Link>
                            <Link to="/pricing">
                                <Button variant="outline" size="lg" className="h-14 px-8 text-lg rounded-full border-2 border-brand-black hover:bg-secondary hover:text-black transition-all hover:scale-105">
                                    View Pricing
                                </Button>
                            </Link>
                        </div>
                    </motion.div>

                    {/* Right Column: Doodle/Illustration */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9, rotate: 2 }}
                        animate={{ opacity: 1, scale: 1, rotate: 0 }}
                        transition={{ duration: 0.8, delay: 0.2 }}
                        className="relative hidden lg:block"
                    >
                        {/* This is the container for your doodle */}
                        <div className="relative w-full aspect-square max-w-[600px] mx-auto flex items-center justify-center translate-x-10">
                            {/* Placeholder / Image Area */}
                            <img 
                                src={planningIllustration} 
                                alt="SAT Prep Illustration" 
                                className="relative z-10 w-full h-auto object-contain"
                            />
                        </div>
                    </motion.div>
                </div>

                {/* Abstract Background Elements */}
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 -z-10 w-[200%] h-[200%] opacity-[0.03] pointer-events-none">
                     <div className="absolute top-0 left-0 w-full h-full bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-brand-blue via-transparent to-transparent" />
                </div>
            </section>

            {/* Feature Grid - "Bento" Style */}
            <section className="py-24 px-6 bg-white relative">
                <div className="max-w-7xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 40 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-100px" }}
                        transition={{ duration: 0.7 }}
                        className="grid grid-cols-1 md:grid-cols-4 gap-6 md:gap-8"
                    >
                        {/* Card 1: Question Bank (Row 1 Left - Width 2) */}
                        <div className="bg-slate-100 text-slate-900 rounded-[2.5rem] p-8 md:p-10 shadow-sm transition-all duration-200 group md:col-span-2 relative overflow-hidden hover:scale-105 hover:shadow-xl">
                             {/* Removed gradient background */}
                             
                             <div className="flex flex-col md:flex-row items-center gap-8 h-full relative z-10">
                                <div className="flex-1 md:flex-[1.4]">
                                    <h3 className="text-3xl font-serif font-medium mb-3">1000+ Highly-Realistic Questions</h3>
                                    <p className="text-lg text-slate-600">Get access to a  growing library of SAT questions generated using our state-of-the-art AI models.</p>
                                </div>
                                <div className="flex-1 w-full max-w-xs">
                                   <div className="relative h-48 w-full overflow-hidden mask-gradient-b">
                                   <div className="absolute top-0 left-0 w-full flex flex-col gap-1.5 opacity-80">
                                      {/* Visual Representation of Question List */}
                                      <motion.div 
                                        className="bg-white p-3.5 rounded-xl flex items-center gap-3 shadow-sm border border-slate-200"
                                        style={{ willChange: "transform" }}
                                        animate={{ y: [0, -4, 0] }}
                                        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                                      >
                                          <div className="w-8 h-8 rounded-full bg-brand-blue/20 flex items-center justify-center text-brand-blue text-xs font-bold">1</div>
                                          <div className="flex-1 space-y-2">
                                              <div className="h-2 w-3/4 bg-slate-200 rounded-full"></div>
                                              <div className="h-2 w-1/2 bg-slate-200 rounded-full"></div>
                                          </div>
                                      </motion.div>
                                      <motion.div 
                                        className="bg-white p-3.5 rounded-xl flex items-center gap-3 shadow-sm border border-slate-200"
                                        style={{ willChange: "transform" }}
                                        animate={{ y: [0, -4, 0] }}
                                        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut", delay: 1 }}
                                      >
                                          <div className="w-8 h-8 rounded-full bg-brand-blue/20 flex items-center justify-center text-brand-blue text-xs font-bold">2</div>
                                          <div className="flex-1 space-y-2">
                                              <div className="h-2 w-full bg-slate-200 rounded-full"></div>
                                              <div className="h-2 w-2/3 bg-slate-200 rounded-full"></div>
                                          </div>
                                      </motion.div>
                                      <motion.div 
                                        className="bg-white p-3.5 rounded-xl flex items-center gap-3 shadow-sm border border-slate-200"
                                        style={{ willChange: "transform" }}
                                        animate={{ y: [0, -4, 0] }}
                                        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut", delay: 2 }}
                                      >
                                          <div className="w-8 h-8 rounded-full bg-brand-blue/20 flex items-center justify-center text-brand-blue text-xs font-bold">3</div>
                                          <div className="flex-1 space-y-2">
                                              <div className="h-2 w-5/6 bg-slate-200 rounded-full"></div>
                                          </div>
                                      </motion.div>
                                   </div>
                                </div>
                             </div>
                        </div>
                        </div>

                         {/* Card 2: Progress Tracker (Row 1 Middle - Width 1) */}
                        <div className="bg-slate-100 text-slate-900 rounded-[2.5rem] p-8 md:p-10 shadow-sm transition-all duration-200 group relative overflow-hidden md:col-span-1 hover:scale-105 hover:shadow-xl">
                             <h3 className="text-2xl font-serif font-medium mb-3">Progress Tracker</h3>
                             <p className="text-base text-slate-600 mb-6">
                                 Visualize your progress, strengths, and weaknesses
                             </p>
                             
                             {/* Mini Graphic */}
                             <div className="mt-auto flex items-end gap-2 h-24">
                                 <motion.div 
                                    className="w-1/5 bg-brand-blue/20 rounded-t-sm h-full origin-bottom" 
                                    style={{ willChange: "transform" }}
                                    animate={{ scaleY: [0.4, 0.45, 0.35, 0.5, 0.4] }}
                                    transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                                 ></motion.div>
                                 <motion.div 
                                    className="w-1/5 bg-brand-blue/40 rounded-t-sm h-full origin-bottom"
                                    style={{ willChange: "transform" }}
                                    animate={{ scaleY: [0.6, 0.7, 0.55, 0.65, 0.6] }}
                                    transition={{ duration: 5, repeat: Infinity, ease: "easeInOut", delay: 0.5 }}
                                 ></motion.div>
                                 <motion.div 
                                    className="w-1/5 bg-brand-blue/60 rounded-t-sm h-full origin-bottom"
                                    style={{ willChange: "transform" }}
                                    animate={{ scaleY: [0.5, 0.6, 0.45, 0.55, 0.5] }}
                                    transition={{ duration: 4.5, repeat: Infinity, ease: "easeInOut", delay: 1 }}
                                 ></motion.div>
                                 <motion.div 
                                    className="w-1/5 bg-brand-blue/80 rounded-t-sm h-full origin-bottom"
                                    style={{ willChange: "transform" }}
                                    animate={{ scaleY: [0.8, 0.7, 0.85, 0.75, 0.8] }}
                                    transition={{ duration: 5.5, repeat: Infinity, ease: "easeInOut", delay: 1.5 }}
                                 ></motion.div>
                                 <motion.div 
                                    className="w-1/5 bg-brand-blue rounded-t-sm h-full origin-bottom"
                                    style={{ willChange: "transform" }}
                                    animate={{ scaleY: [0.9, 0.95, 0.85, 1, 0.9] }}
                                    transition={{ duration: 6, repeat: Infinity, ease: "easeInOut", delay: 2 }}
                                 ></motion.div>
                             </div>
                        </div>

                        {/* Card 5: Exam Simulator (Row 1 Right - Width 1, Height 2) */}
                        <div className="bg-slate-100 text-slate-900 rounded-[2.5rem] p-8 md:p-10 shadow-sm transition-all duration-200 group relative overflow-hidden flex flex-col md:col-span-1 md:row-span-2 hover:scale-105 hover:shadow-xl">
                             <div className="relative z-10 flex-1 flex flex-col">
                                <h3 className="text-3xl font-serif font-medium mb-4">1:1 Exam Simulator</h3>
                                <p className="text-lg text-slate-600 mb-8">
                                    Experience test day pressure with our realistic interface
                                </p>
                                <div className="mt-auto w-full transform bg-white text-slate-900 rounded-2xl shadow-lg p-5 rotate-3 group-hover:rotate-0 transition-transform duration-500 border border-slate-200 origin-center scale-100">
                                    <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-3">
                                        <div className="text-[10px] font-bold text-slate-400 tracking-wider">R&W • MODULE 2</div>
                                        <div className="text-xs font-mono font-bold text-red-500 bg-red-50 px-2 py-0.5 rounded">4:45</div>
                                    </div>
                                    <div className="space-y-2 mb-6">
                                        <div className="h-1.5 w-full bg-slate-200 rounded-full"></div>
                                        <div className="h-1.5 w-11/12 bg-slate-200 rounded-full"></div>
                                        <div className="h-1.5 w-5/6 bg-slate-200 rounded-full"></div>
                                    </div>
                                    <div className="space-y-2">
                                        <div className="flex items-center gap-3 p-2 rounded-lg border border-slate-200">
                                            <div className="h-5 w-5 rounded flex items-center justify-center bg-slate-200 text-[10px] font-bold text-slate-700">A</div>
                                            <div className="h-1.5 w-16 bg-slate-200 rounded-full"></div>
                                        </div>
                                        <div className="flex items-center gap-3 p-2 rounded-lg border border-brand-blue/30 bg-blue-50/50 relative overflow-hidden">
                                            <motion.div 
                                                className="absolute inset-0 bg-blue-100/50 z-0"
                                                initial={{ x: "-100%" }}
                                                animate={{ x: "100%" }}
                                                transition={{ duration: 2, repeat: Infinity, ease: "linear", repeatDelay: 1 }}
                                            />
                                            <div className="h-5 w-5 rounded flex items-center justify-center bg-brand-blue text-[10px] font-bold text-white shadow-sm z-10 relative">B</div>
                                            <div className="h-1.5 w-24 bg-brand-blue/20 rounded-full z-10 relative"></div>
                                        </div>
                                        <div className="flex items-center gap-3 p-2 rounded-lg border border-slate-200">
                                            <div className="h-5 w-5 rounded flex items-center justify-center bg-slate-200 text-[10px] font-bold text-slate-700">C</div>
                                            <div className="h-1.5 w-20 bg-slate-200 rounded-full"></div>
                                        </div>
                                        <div className="flex items-center gap-3 p-2 rounded-lg border border-slate-200">
                                            <div className="h-5 w-5 rounded flex items-center justify-center bg-slate-200 text-[10px] font-bold text-slate-700">D</div>
                                            <div className="h-1.5 w-12 bg-slate-200 rounded-full"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                         {/* Card 3: Socials (Row 2 Left - Width 1) */}
                         <div className="bg-slate-100 text-slate-900 rounded-[2.5rem] p-8 md:p-10 shadow-sm transition-all duration-200 group relative overflow-hidden md:col-span-1 hover:scale-105 hover:shadow-xl">
                            <div className="flex items-center justify-between mb-6">
                                <div className="p-3 bg-white rounded-2xl border border-slate-200 shadow-sm">
                                    <Users className="w-6 h-6 text-brand-blue" />
                                </div>
                            </div>
                            <h3 className="text-2xl font-serif font-medium mb-3">Social Learning</h3>
                            <p className="text-base text-slate-600 mb-6">
                                See friends' progress and compete on the leaderboard
                            </p>
                            <div className="flex -space-x-3 mt-auto pt-4 isolate">
                                <motion.div 
                                    className="w-10 h-10 rounded-full border-2 border-slate-100 bg-slate-200 flex items-center justify-center text-xs font-medium text-slate-900 relative z-40"
                                    style={{ willChange: "transform" }}
                                    animate={{ y: [0, -5, 0] }}
                                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut", delay: 0 }}
                                >JD</motion.div>
                                <motion.div 
                                    className="w-10 h-10 rounded-full border-2 border-slate-100 bg-blue-100 flex items-center justify-center text-xs font-medium text-brand-blue relative z-30"
                                    style={{ willChange: "transform" }}
                                    animate={{ y: [0, -5, 0] }}
                                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut", delay: 0.5 }}
                                >AS</motion.div>
                                <motion.div 
                                    className="w-10 h-10 rounded-full border-2 border-slate-100 bg-purple-100 flex items-center justify-center text-xs font-medium text-purple-600 relative z-20"
                                    style={{ willChange: "transform" }}
                                    animate={{ y: [0, -5, 0] }}
                                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut", delay: 1 }}
                                >MK</motion.div>
                                <motion.div 
                                    className="w-10 h-10 rounded-full border-2 border-slate-100 bg-white flex items-center justify-center text-xs font-medium text-slate-600 relative z-10"
                                    style={{ willChange: "transform" }}
                                    animate={{ y: [0, -5, 0] }}
                                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut", delay: 1.5 }}
                                >+3</motion.div>
                            </div>
                         </div>

                         {/* Card 4: Targeted Practice (Row 2 Middle - Width 2) */}
                         <div className="bg-slate-100 text-slate-900 rounded-[2.5rem] p-8 md:p-10 shadow-sm transition-all duration-200 flex flex-col justify-between relative overflow-hidden group md:col-span-2 hover:scale-105 hover:shadow-xl">
                               <div className="relative z-10 flex flex-col items-start h-full justify-between">
                                   <div>
                                       <h3 className="text-3xl font-serif font-medium mb-4">Targeted Practice</h3>
                                       <p className="text-slate-600 leading-relaxed max-w-sm">
                                           Choose exactly which types of questions to practice. Filter by specific domains, skills, or themes
                                       </p>
                                   </div>
                               
                                   <div className="mt-8 w-full overflow-hidden" style={{ maskImage: 'linear-gradient(to right, transparent, black 10%, black 90%, transparent)', WebkitMaskImage: 'linear-gradient(to right, transparent, black 10%, black 90%, transparent)' }}>
                                        {/* Row 1: Skills (Scroll Left, Infinite Loop) */}
                                        <motion.div 
                                            className="flex gap-3 mb-3 whitespace-nowrap"
                                            animate={{ x: ["0%", "-50%"] }}
                                            transition={{ repeat: Infinity, repeatType: "loop", ease: "linear", duration: 40 }}
                                        >
                                            {([
                                                "Inferences", "Command of Evidence", "Central Ideas and Details", "Words in Context", "Text Structure and Purpose", "Standard English Conventions", "Rhetorical Synthesis", "Transitions", "Form, Structure, and Sense", "Boundaries"
                                            ].concat([
                                                "Inferences", "Command of Evidence", "Central Ideas and Details", "Words in Context", "Text Structure and Purpose", "Standard English Conventions", "Rhetorical Synthesis", "Transitions", "Form, Structure, and Sense", "Boundaries"
                                            ])).map((skill, i) => (
                                                <div key={i} className="px-3 py-1.5 rounded-md bg-white text-xs border border-slate-200 text-slate-700 shrink-0 shadow-sm">
                                                    {skill}
                                                </div>
                                            ))}
                                        </motion.div>

                                        {/* Row 2: Subtopics (Scroll Right, Infinite Loop) */}
                                        <motion.div 
                                            className="flex gap-3 whitespace-nowrap"
                                            animate={{ x: ["-50%", "0%"] }}
                                            transition={{ repeat: Infinity, repeatType: "loop", ease: "linear", duration: 45 }}
                                        >
                                            {([
                                                "Psychology", "Economics", "Sociology", "Political Science", "Biology", "Physics", "Classic Fiction", "Visual Arts", "Philosophy", "Earth Science"
                                            ].concat([
                                                "Psychology", "Economics", "Sociology", "Political Science", "Biology", "Physics", "Classic Fiction", "Visual Arts", "Philosophy", "Earth Science"
                                            ])).map((topic, i) => (
                                                <div key={i} className="px-3 py-1.5 rounded-md bg-white text-xs border border-slate-200 text-slate-700 shrink-0 shadow-sm">
                                                    {topic}
                                                </div>
                                            ))}
                                        </motion.div>
                                   </div>
                               </div>
                         </div>

                    </motion.div>
                </div>
            </section>

            {/* Bottom CTA */}
            <section className="py-32 px-6">
                <div className="w-full px-0 md:auto flex flex-col md:flex-row items-center justify-between gap-12">
                        {/* Left: Text Content */}
                        <div className="max-w-7xl mx-auto w-full px-6 flex flex-col md:flex-row items-center justify-between gap-12">
                    <div className="flex-1 text-left">
                        <h2 className="text-4xl md:text-5xl font-serif font-medium mb-6">Ready to hit your 1550+?</h2>
                        <p className="text-xl text-muted-foreground mb-10">Join thousands of students who have upgraded their prep.</p>
                        <Link to="/auth">
                            <Button size="lg" className="h-16 px-12 text-xl rounded-full bg-foreground text-background hover:bg-foreground/90 transition-all hover:scale-105 shadow-xl shadow-black/5">
                                Get Started for Free
                            </Button>
                        </Link>
                    </div>
                    {/* Right: Image */}
                    <div className="flex-1 flex justify-center items-center translate-x-20">
                        <img 
                            src={targetScribble} 
                            alt="Target with arrows illustration" 
                            className="w-full max-w-xs md:max-w-sm lg:max-w-md h-auto"
                        />
                    </div>
                </div>
                </div>
            </section>

            <Footer />
        </div>
    );
};

export default Index;
